# 1.7 Introduction to numpy

Plan:

- Creating arrays
- Multi-dimensional arrays
- Randomly generated arrays
- Element-wise operations
  - Comparison operations
  - Logical operations
- summarizing operations 

In [1]:
import numpy as np

# Creating Arrays

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10) 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
a = np.array([1,2,3,5,7,12])

In [7]:
a[2]

np.int64(3)

In [10]:
a[2] = 10

In [11]:
a

array([ 1,  2, 10,  5,  7, 12])

In [13]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [18]:
np.linspace(0,100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Multi-dimensional Arrays

In [21]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [29]:
n[0, 1] = 20

In [30]:
n[0, 1]

np.int64(20)

In [33]:
n[2] = np.ones(3)

In [34]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [40]:
n[:,2]

array([3, 6, 1])

In [41]:
n[:]

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [42]:
n[:,2] = [0,1,2]

In [43]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

# Randomly generated arrays

In [58]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [59]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [60]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [61]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Element-wise operations

In [62]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [63]:
a + 1

array([1, 2, 3, 4, 5])

In [64]:
a * 2

array([0, 2, 4, 6, 8])

In [65]:
a / 100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [68]:
b = (10 + (a * 2)) ** 2 / 100

In [70]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [71]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

# Comparison Operations

In [72]:
a

array([0, 1, 2, 3, 4])

In [74]:
a >= 2

array([False, False,  True,  True,  True])

In [75]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [76]:
a > b

array([False, False,  True,  True,  True])

In [77]:
~ (a > b)

array([ True,  True, False, False, False])

In [78]:
a[a > b]

array([2, 3, 4])

# Summarizing Operations

In [80]:
a

array([0, 1, 2, 3, 4])

In [81]:
a.min()

np.int64(0)

In [82]:
a.sum()

np.int64(10)

In [83]:
a.mean()

np.float64(2.0)

In [84]:
a.std()

np.float64(1.4142135623730951)

In [85]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

In [86]:
n.sum()

np.int64(35)

In [87]:
n.min()

np.int64(0)